// Generated by rstantools.  Do not edit by hand.

#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.26.1-4-gd72b68b7-dirty
#include <stan/model/model_header.hpp>
namespace model_multi_steep_fixed_sd_fixed_k_namespace {
inline void validate_positive_index(const char* var_name, const char* expr,
                                    int val) {
  if (val < 1) {
    std::stringstream msg;
    msg << "Found dimension size less than one in simplex declaration"
        << "; variable=" << var_name << "; dimension size expression=" << expr
        << "; expression value=" << val;
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}
inline void validate_unit_vector_index(const char* var_name, const char* expr,
                                       int val) {
  if (val <= 1) {
    std::stringstream msg;
    if (val == 1) {
      msg << "Found dimension size one in unit vector declaration."
          << " One-dimensional unit vector is discrete"
          << " but the target distribution must be continuous."
          << " variable=" << var_name << "; dimension size expression=" << expr;
    } else {
      msg << "Found dimension size less than one in unit vector declaration"
          << "; variable=" << var_name << "; dimension size expression=" << expr
          << "; expression value=" << val;
    }
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using std::pow;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using stan::model::cons_list;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::nil_index_list;
using namespace stan::math;
using stan::math::pow; 
stan::math::profile_map profiles__;
static int current_statement__= 0;
static const std::vector<string> locations_array__ = {" (found before start of program)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 121, column 2 to column 33)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 125, column 2 to column 29)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 128, column 6 to column 68)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 127, column 19 to line 129, column 5)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 127, column 4 to line 129, column 5)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 126, column 22 to line 130, column 3)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 126, column 2 to line 130, column 3)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 140, column 2 to column 27)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 141, column 2 to column 32)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 143, column 4 to column 113)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 144, column 4 to column 71)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 142, column 22 to line 145, column 3)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 142, column 2 to line 145, column 3)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 135, column 4 to column 37)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 136, column 4 to column 105)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 133, column 22 to line 137, column 3)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 133, column 2 to line 137, column 3)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 111, column 2 to column 17)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 112, column 2 to column 17)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 113, column 2 to column 22)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 114, column 8 to column 9)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 114, column 11 to column 17)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 114, column 2 to column 39)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 115, column 8 to column 9)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 115, column 11 to column 17)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 115, column 2 to column 38)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 116, column 9 to column 10)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 116, column 12 to column 13)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 116, column 2 to column 24)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 117, column 8 to column 14)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 117, column 2 to column 32)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 118, column 8 to column 9)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 118, column 2 to column 26)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 121, column 9 to column 15)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 121, column 17 to column 18)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 125, column 9 to column 15)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 125, column 17 to column 18)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 140, column 9 to column 15)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 141, column 9 to column 15)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 141, column 17 to column 18)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 3, column 10 to column 11)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 3, column 4 to column 25)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 4, column 4 to column 15)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 5, column 11 to column 12)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 5, column 4 to column 21)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 7, column 6 to column 30)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 6, column 19 to line 8, column 5)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 6, column 4 to line 8, column 5)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 11, column 6 to column 86)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 13, column 6 to column 80)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 15, column 6 to column 34)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 17, column 6 to column 64)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 18, column 6 to column 62)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 9, column 19 to line 19, column 7)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 9, column 4 to line 19, column 7)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 20, column 4 to column 18)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 2, column 135 to line 21, column 3)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 23, column 4 to column 19)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 24, column 4 to column 15)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 25, column 11 to column 16)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 25, column 18 to column 23)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 25, column 4 to column 43)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 26, column 11 to column 16)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 26, column 4 to column 30)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 28, column 11 to column 16)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 28, column 4 to column 25)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 30, column 6 to column 30)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 29, column 23 to line 31, column 5)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 29, column 4 to line 31, column 5)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 33, column 6 to column 80)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 35, column 6 to column 34)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 37, column 6 to column 64)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 38, column 6 to column 62)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 32, column 32 to line 39, column 5)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 32, column 4 to line 39, column 5)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 42, column 8 to column 55)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 43, column 8 to column 44)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 44, column 8 to column 50)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 41, column 31 to line 45, column 7)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 41, column 6 to line 45, column 7)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 40, column 29 to line 46, column 5)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 40, column 4 to line 46, column 5)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 48, column 6 to column 36)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 49, column 6 to column 51)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 47, column 23 to line 50, column 5)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 47, column 4 to line 50, column 5)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 51, column 4 to column 23)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 22, column 128 to line 52, column 3)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 55, column 11 to column 16)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 55, column 4 to column 21)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 56, column 11 to column 16)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 56, column 4 to column 21)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 57, column 11 to column 16)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 57, column 4 to column 21)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 58, column 11 to column 16)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 58, column 4 to column 22)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 60, column 4 to column 15)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 61, column 4 to column 16)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 62, column 4 to column 15)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 63, column 4 to column 16)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 65, column 11 to column 16)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 65, column 4 to column 27)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 66, column 4 to column 10)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 67, column 4 to column 10)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 69, column 4 to column 21)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 72, column 6 to column 12)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 73, column 6 to column 12)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 76, column 10 to column 20)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 75, column 29 to line 77, column 9)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 75, column 8 to line 77, column 9)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 79, column 10 to column 20)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 78, column 30 to line 80, column 9)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 78, column 8 to line 80, column 9)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 74, column 21 to line 81, column 7)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 74, column 6 to line 81, column 7)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 84, column 10 to column 20)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 83, column 29 to line 85, column 9)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 83, column 8 to line 85, column 9)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 87, column 10 to column 20)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 86, column 30 to line 88, column 9)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 86, column 8 to line 88, column 9)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 82, column 33 to line 89, column 7)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 82, column 6 to line 89, column 7)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 90, column 6 to column 44)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 71, column 23 to line 91, column 5)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 71, column 4 to line 91, column 5)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 93, column 4 to column 21)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 94, column 4 to column 17)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 96, column 6 to column 40)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 95, column 23 to line 97, column 5)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 95, column 4 to line 97, column 5)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 98, column 4 to column 26)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 99, column 4 to column 34)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 100, column 4 to column 89)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 102, column 4 to column 35)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 103, column 4 to column 25)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 104, column 4 to column 19)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 105, column 4 to column 18)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 106, column 4 to column 35)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 107, column 4 to column 18)",
                                                      " (in 'multi_steep_fixed_sd_fixed_k', line 53, column 54 to line 108, column 3)"};
template <typename T0__, typename T1__, typename T2__>
std::vector<stan::promote_args_t<stan::value_type_t<T0__>, T1__,
stan::value_type_t<T2__>>>
ProbFunction(const T0__& EloStart_arg__, const T1__& k,
             const T2__& presence_arg__, const int& N, const int& K,
             const std::vector<int>& winner_index,
             const std::vector<int>& loser_index, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::value_type_t<T0__>,
          T1__,
          stan::value_type_t<T2__>>;
  const auto& EloStart = to_ref(EloStart_arg__);
  const auto& presence = to_ref(presence_arg__);
  const static bool propto__ = true;
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  (void) DUMMY_VAR__;  // suppress unused var warning
  
  try {
    current_statement__ = 41;
    validate_non_negative_index("result", "N", N);
    std::vector<local_scalar_t__> result;
    result = std::vector<local_scalar_t__>(N, DUMMY_VAR__);
    
    local_scalar_t__ toAdd;
    toAdd = DUMMY_VAR__;
    
    current_statement__ = 44;
    validate_non_negative_index("EloNow", "K", K);
    Eigen::Matrix<local_scalar_t__, -1, 1> EloNow;
    EloNow = Eigen::Matrix<local_scalar_t__, -1, 1>(K);
    stan::math::fill(EloNow, DUMMY_VAR__);
    
    current_statement__ = 48;
    for (int j = 1; j <= K; ++j) {
      current_statement__ = 46;
      assign(EloNow, cons_list(index_uni(j), nil_index_list()),
        EloStart[(j - 1)], "assigning variable EloNow");}
    current_statement__ = 55;
    for (int i = 1; i <= N; ++i) {
      current_statement__ = 49;
      assign(EloNow, nil_index_list(),
        subtract(stan::model::deep_copy(EloNow),
          (dot_product(row(presence, i), EloNow) / sum(row(presence, i)))),
        "assigning variable EloNow");
      current_statement__ = 50;
      assign(result, cons_list(index_uni(i), nil_index_list()),
        (1 /
          (1 +
            stan::math::exp(
              (EloNow[(loser_index[(i - 1)] - 1)] -
                EloNow[(winner_index[(i - 1)] - 1)])))),
        "assigning variable result");
      current_statement__ = 51;
      toAdd = ((1 - result[(i - 1)]) * k);
      current_statement__ = 52;
      assign(EloNow,
        cons_list(index_uni(winner_index[(i - 1)]), nil_index_list()),
        (EloNow[(winner_index[(i - 1)] - 1)] + toAdd),
        "assigning variable EloNow");
      current_statement__ = 53;
      assign(EloNow,
        cons_list(index_uni(loser_index[(i - 1)]), nil_index_list()),
        (EloNow[(loser_index[(i - 1)] - 1)] - toAdd),
        "assigning variable EloNow");}
    current_statement__ = 56;
    return result;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
  }
  
}
struct ProbFunction_functor__ {
template <typename T0__, typename T1__, typename T2__>
std::vector<stan::promote_args_t<stan::value_type_t<T0__>, T1__,
stan::value_type_t<T2__>>>
operator()(const T0__& EloStart, const T1__& k, const T2__& presence,
           const int& N, const int& K, const std::vector<int>& winner_index,
           const std::vector<int>& loser_index, std::ostream* pstream__)  const 
{
return ProbFunction(EloStart, k, presence, N, K, winner_index, loser_index,
         pstream__);
}
};
template <typename T0__, typename T1__>
Eigen::Matrix<stan::promote_args_t<stan::value_type_t<T0__>,
T1__>, -1, 1>
cum_winprob(const T0__& EloStart_arg__, const T1__& k,
            const int& n_interactions, const int& n_ids,
            const std::vector<int>& winner_index,
            const std::vector<int>& loser_index, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::value_type_t<T0__>,
          T1__>;
  const auto& EloStart = to_ref(EloStart_arg__);
  const static bool propto__ = true;
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  (void) DUMMY_VAR__;  // suppress unused var warning
  
  try {
    local_scalar_t__ single_wp;
    single_wp = DUMMY_VAR__;
    
    local_scalar_t__ toAdd;
    toAdd = DUMMY_VAR__;
    
    current_statement__ = 60;
    validate_non_negative_index("pairwise_winprobs", "n_ids", n_ids);
    current_statement__ = 61;
    validate_non_negative_index("pairwise_winprobs", "n_ids", n_ids);
    Eigen::Matrix<local_scalar_t__, -1, -1> pairwise_winprobs;
    pairwise_winprobs = Eigen::Matrix<local_scalar_t__, -1, -1>(n_ids, n_ids);
    stan::math::fill(pairwise_winprobs, DUMMY_VAR__);
    
    current_statement__ = 63;
    validate_non_negative_index("cumwinprobs", "n_ids", n_ids);
    Eigen::Matrix<local_scalar_t__, -1, 1> cumwinprobs;
    cumwinprobs = Eigen::Matrix<local_scalar_t__, -1, 1>(n_ids);
    stan::math::fill(cumwinprobs, DUMMY_VAR__);
    
    current_statement__ = 65;
    validate_non_negative_index("EloNow", "n_ids", n_ids);
    Eigen::Matrix<local_scalar_t__, -1, 1> EloNow;
    EloNow = Eigen::Matrix<local_scalar_t__, -1, 1>(n_ids);
    stan::math::fill(EloNow, DUMMY_VAR__);
    
    current_statement__ = 69;
    for (int j = 1; j <= n_ids; ++j) {
      current_statement__ = 67;
      assign(EloNow, cons_list(index_uni(j), nil_index_list()),
        EloStart[(j - 1)], "assigning variable EloNow");}
    current_statement__ = 75;
    for (int i = 1; i <= n_interactions; ++i) {
      current_statement__ = 70;
      single_wp = (1 /
                    (1 +
                      stan::math::exp(
                        (EloNow[(loser_index[(i - 1)] - 1)] -
                          EloNow[(winner_index[(i - 1)] - 1)]))));
      current_statement__ = 71;
      toAdd = ((1 - single_wp) * k);
      current_statement__ = 72;
      assign(EloNow,
        cons_list(index_uni(winner_index[(i - 1)]), nil_index_list()),
        (EloNow[(winner_index[(i - 1)] - 1)] + toAdd),
        "assigning variable EloNow");
      current_statement__ = 73;
      assign(EloNow,
        cons_list(index_uni(loser_index[(i - 1)]), nil_index_list()),
        (EloNow[(loser_index[(i - 1)] - 1)] - toAdd),
        "assigning variable EloNow");}
    current_statement__ = 82;
    for (int i = 1; i <= (n_ids - 1); ++i) {
      current_statement__ = 80;
      for (int j = (i + 1); j <= n_ids; ++j) {
        current_statement__ = 76;
        single_wp = (1 /
                      (1 +
                        stan::math::exp((EloNow[(i - 1)] - EloNow[(j - 1)]))));
        current_statement__ = 77;
        assign(pairwise_winprobs,
          cons_list(index_uni(j), cons_list(index_uni(i), nil_index_list())),
          single_wp, "assigning variable pairwise_winprobs");
        current_statement__ = 78;
        assign(pairwise_winprobs,
          cons_list(index_uni(i), cons_list(index_uni(j), nil_index_list())),
          (1.0 - single_wp), "assigning variable pairwise_winprobs");}}
    current_statement__ = 86;
    for (int i = 1; i <= n_ids; ++i) {
      current_statement__ = 83;
      assign(pairwise_winprobs,
        cons_list(index_uni(i), cons_list(index_uni(i), nil_index_list())),
        0.0, "assigning variable pairwise_winprobs");
      current_statement__ = 84;
      assign(cumwinprobs, cons_list(index_uni(i), nil_index_list()),
        sum(
          rvalue(pairwise_winprobs,
            cons_list(index_uni(i),
              cons_list(index_omni(), nil_index_list())),
            "pairwise_winprobs")), "assigning variable cumwinprobs");}
    current_statement__ = 87;
    return cumwinprobs;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
  }
  
}
struct cum_winprob_functor__ {
template <typename T0__, typename T1__>
Eigen::Matrix<stan::promote_args_t<stan::value_type_t<T0__>,
T1__>, -1, 1>
operator()(const T0__& EloStart, const T1__& k, const int& n_interactions,
           const int& n_ids, const std::vector<int>& winner_index,
           const std::vector<int>& loser_index, std::ostream* pstream__)  const 
{
return cum_winprob(EloStart, k, n_interactions, n_ids, winner_index,
         loser_index, pstream__);
}
};
template <typename T0__>
Eigen::Matrix<stan::promote_args_t<stan::value_type_t<T0__>>, -1, 1>
cumwinprob2steep(const T0__& nds_arg__, const int& n_ids,
                 std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::value_type_t<T0__>>;
  const auto& nds = to_ref(nds_arg__);
  const static bool propto__ = true;
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  (void) DUMMY_VAR__;  // suppress unused var warning
  
  try {
    current_statement__ = 89;
    validate_non_negative_index("A1", "n_ids", n_ids);
    Eigen::Matrix<local_scalar_t__, -1, 1> A1;
    A1 = Eigen::Matrix<local_scalar_t__, -1, 1>(n_ids);
    stan::math::fill(A1, DUMMY_VAR__);
    
    current_statement__ = 91;
    validate_non_negative_index("A2", "n_ids", n_ids);
    Eigen::Matrix<local_scalar_t__, -1, 1> A2;
    A2 = Eigen::Matrix<local_scalar_t__, -1, 1>(n_ids);
    stan::math::fill(A2, DUMMY_VAR__);
    
    current_statement__ = 93;
    validate_non_negative_index("B1", "n_ids", n_ids);
    Eigen::Matrix<local_scalar_t__, -1, 1> B1;
    B1 = Eigen::Matrix<local_scalar_t__, -1, 1>(n_ids);
    stan::math::fill(B1, DUMMY_VAR__);
    
    current_statement__ = 95;
    validate_non_negative_index("AB1", "n_ids", n_ids);
    Eigen::Matrix<local_scalar_t__, -1, 1> AB1;
    AB1 = Eigen::Matrix<local_scalar_t__, -1, 1>(n_ids);
    stan::math::fill(AB1, DUMMY_VAR__);
    
    local_scalar_t__ sum_y;
    sum_y = DUMMY_VAR__;
    
    local_scalar_t__ sum_x2;
    sum_x2 = DUMMY_VAR__;
    
    local_scalar_t__ sum_x;
    sum_x = DUMMY_VAR__;
    
    local_scalar_t__ sum_xy;
    sum_xy = DUMMY_VAR__;
    
    current_statement__ = 101;
    validate_non_negative_index("theranks", "n_ids", n_ids);
    Eigen::Matrix<local_scalar_t__, -1, 1> theranks;
    theranks = Eigen::Matrix<local_scalar_t__, -1, 1>(n_ids);
    stan::math::fill(theranks, DUMMY_VAR__);
    
    int r;
    r = std::numeric_limits<int>::min();
    
    int s;
    s = std::numeric_limits<int>::min();
    
    Eigen::Matrix<local_scalar_t__, -1, 1> xsteep;
    xsteep = Eigen::Matrix<local_scalar_t__, -1, 1>(2);
    stan::math::fill(xsteep, DUMMY_VAR__);
    
    current_statement__ = 126;
    for (int i = 1; i <= n_ids; ++i) {
      current_statement__ = 106;
      r = 1;
      current_statement__ = 107;
      s = 1;
      current_statement__ = 115;
      for (int j = 1; j <= i; ++j) {
        current_statement__ = 110;
        if (logical_lt(nds[(j - 1)], nds[(i - 1)])) {
          current_statement__ = 108;
          r = (r + 1);
        } 
        current_statement__ = 113;
        if (logical_eq(nds[(j - 1)], nds[(i - 1)])) {
          current_statement__ = 111;
          s = (s + 1);
        } }
      current_statement__ = 123;
      for (int j = (i + 1); j <= n_ids; ++j) {
        current_statement__ = 118;
        if (logical_lt(nds[(j - 1)], nds[(i - 1)])) {
          current_statement__ = 116;
          r = (r + 1);
        } 
        current_statement__ = 121;
        if (logical_eq(nds[(j - 1)], nds[(i - 1)])) {
          current_statement__ = 119;
          s = (s + 1);
        } }
      current_statement__ = 124;
      assign(theranks, cons_list(index_uni(i), nil_index_list()),
        ((r + ((s - 1) * 0.5)) - 0.5), "assigning variable theranks");}
    current_statement__ = 127;
    sum_y = sum(nds);
    current_statement__ = 128;
    sum_x2 = 0.0;
    current_statement__ = 131;
    for (int i = 1; i <= n_ids; ++i) {
      current_statement__ = 129;
      sum_x2 = (sum_x2 + pow(theranks[(i - 1)], 2));}
    current_statement__ = 132;
    sum_x = sum(theranks);
    current_statement__ = 133;
    sum_xy = sum(elt_multiply(nds, theranks));
    current_statement__ = 134;
    assign(xsteep, cons_list(index_uni(1), nil_index_list()),
      (((sum_y * sum_x2) - (sum_x * sum_xy)) /
        ((n_ids * sum_x2) - pow(sum_x, 2))), "assigning variable xsteep");
    current_statement__ = 135;
    assign(A1, nil_index_list(), subtract(theranks, mean(theranks)),
      "assigning variable A1");
    current_statement__ = 136;
    assign(B1, nil_index_list(), subtract(nds, mean(nds)),
      "assigning variable B1");
    current_statement__ = 137;
    assign(AB1, nil_index_list(), elt_multiply(A1, B1),
      "assigning variable AB1");
    current_statement__ = 138;
    assign(A2, nil_index_list(), elt_multiply(A1, A1),
      "assigning variable A2");
    current_statement__ = 139;
    assign(xsteep, cons_list(index_uni(2), nil_index_list()),
      (sum(AB1) / sum(A2)), "assigning variable xsteep");
    current_statement__ = 140;
    return xsteep;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
  }
  
}
struct cumwinprob2steep_functor__ {
template <typename T0__>
Eigen::Matrix<stan::promote_args_t<stan::value_type_t<T0__>>, -1, 1>
operator()(const T0__& nds, const int& n_ids, std::ostream* pstream__)  const 
{
return cumwinprob2steep(nds, n_ids, pstream__);
}
};
#include <stan_meta_header.hpp>
class model_multi_steep_fixed_sd_fixed_k final : public model_base_crtp<model_multi_steep_fixed_sd_fixed_k> {
private:
  int N;
  int K;
  int n_rand;
  std::vector<std::vector<int>> winner;
  std::vector<std::vector<int>> loser;
  Eigen::Matrix<double, -1, -1> presence;
  std::vector<double> k;
  std::vector<int> y;
 
public:
  ~model_multi_steep_fixed_sd_fixed_k() { }
  
  inline std::string model_name() const final { return "model_multi_steep_fixed_sd_fixed_k"; }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.26.1-4-gd72b68b7-dirty", "stancflags = "};
  }
  
  
  model_multi_steep_fixed_sd_fixed_k(stan::io::var_context& context__,
                                     unsigned int random_seed__ = 0,
                                     std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static const char* function__ = "model_multi_steep_fixed_sd_fixed_k_namespace::model_multi_steep_fixed_sd_fixed_k";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      current_statement__ = 18;
      context__.validate_dims("data initialization","N","int",
          context__.to_vec());
      N = std::numeric_limits<int>::min();
      
      current_statement__ = 18;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 18;
      current_statement__ = 18;
      check_greater_or_equal(function__, "N", N, 1);
      current_statement__ = 19;
      context__.validate_dims("data initialization","K","int",
          context__.to_vec());
      K = std::numeric_limits<int>::min();
      
      current_statement__ = 19;
      K = context__.vals_i("K")[(1 - 1)];
      current_statement__ = 19;
      current_statement__ = 19;
      check_greater_or_equal(function__, "K", K, 1);
      current_statement__ = 20;
      context__.validate_dims("data initialization","n_rand","int",
          context__.to_vec());
      n_rand = std::numeric_limits<int>::min();
      
      current_statement__ = 20;
      n_rand = context__.vals_i("n_rand")[(1 - 1)];
      current_statement__ = 20;
      current_statement__ = 20;
      check_greater_or_equal(function__, "n_rand", n_rand, 1);
      current_statement__ = 21;
      validate_non_negative_index("winner", "N", N);
      current_statement__ = 22;
      validate_non_negative_index("winner", "n_rand", n_rand);
      current_statement__ = 23;
      context__.validate_dims("data initialization","winner","int",
          context__.to_vec(N, n_rand));
      winner = std::vector<std::vector<int>>(N, std::vector<int>(n_rand, std::numeric_limits<int>::min()));
      
      {
        std::vector<int> winner_flat__;
        current_statement__ = 23;
        assign(winner_flat__, nil_index_list(), context__.vals_i("winner"),
          "assigning variable winner_flat__");
        current_statement__ = 23;
        pos__ = 1;
        current_statement__ = 23;
        for (int sym1__ = 1; sym1__ <= n_rand; ++sym1__) {
          current_statement__ = 23;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 23;
            assign(winner,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              winner_flat__[(pos__ - 1)], "assigning variable winner");
            current_statement__ = 23;
            pos__ = (pos__ + 1);}}
      }
      current_statement__ = 23;
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 23;
        for (int sym2__ = 1; sym2__ <= n_rand; ++sym2__) {
          current_statement__ = 23;
          current_statement__ = 23;
          check_greater_or_equal(function__, "winner[sym1__, sym2__]",
                                 winner[(sym1__ - 1)][(sym2__ - 1)], 1);}}
      current_statement__ = 24;
      validate_non_negative_index("loser", "N", N);
      current_statement__ = 25;
      validate_non_negative_index("loser", "n_rand", n_rand);
      current_statement__ = 26;
      context__.validate_dims("data initialization","loser","int",
          context__.to_vec(N, n_rand));
      loser = std::vector<std::vector<int>>(N, std::vector<int>(n_rand, std::numeric_limits<int>::min()));
      
      {
        std::vector<int> loser_flat__;
        current_statement__ = 26;
        assign(loser_flat__, nil_index_list(), context__.vals_i("loser"),
          "assigning variable loser_flat__");
        current_statement__ = 26;
        pos__ = 1;
        current_statement__ = 26;
        for (int sym1__ = 1; sym1__ <= n_rand; ++sym1__) {
          current_statement__ = 26;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 26;
            assign(loser,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              loser_flat__[(pos__ - 1)], "assigning variable loser");
            current_statement__ = 26;
            pos__ = (pos__ + 1);}}
      }
      current_statement__ = 26;
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 26;
        for (int sym2__ = 1; sym2__ <= n_rand; ++sym2__) {
          current_statement__ = 26;
          current_statement__ = 26;
          check_greater_or_equal(function__, "loser[sym1__, sym2__]",
                                 loser[(sym1__ - 1)][(sym2__ - 1)], 1);}}
      current_statement__ = 27;
      validate_non_negative_index("presence", "N", N);
      current_statement__ = 28;
      validate_non_negative_index("presence", "K", K);
      current_statement__ = 29;
      context__.validate_dims("data initialization","presence","double",
          context__.to_vec(N, K));
      presence = Eigen::Matrix<double, -1, -1>(N, K);
      stan::math::fill(presence, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> presence_flat__;
        current_statement__ = 29;
        assign(presence_flat__, nil_index_list(),
          context__.vals_r("presence"), "assigning variable presence_flat__");
        current_statement__ = 29;
        pos__ = 1;
        current_statement__ = 29;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 29;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 29;
            assign(presence,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              presence_flat__[(pos__ - 1)], "assigning variable presence");
            current_statement__ = 29;
            pos__ = (pos__ + 1);}}
      }
      current_statement__ = 30;
      validate_non_negative_index("k", "n_rand", n_rand);
      current_statement__ = 31;
      context__.validate_dims("data initialization","k","double",
          context__.to_vec(n_rand));
      k = std::vector<double>(n_rand, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 31;
      assign(k, nil_index_list(), context__.vals_r("k"),
        "assigning variable k");
      current_statement__ = 31;
      for (int sym1__ = 1; sym1__ <= n_rand; ++sym1__) {
        current_statement__ = 31;
        current_statement__ = 31;
        check_greater_or_equal(function__, "k[sym1__]", k[(sym1__ - 1)], 0);}
      current_statement__ = 32;
      validate_non_negative_index("y", "N", N);
      current_statement__ = 33;
      context__.validate_dims("data initialization","y","int",
          context__.to_vec(N));
      y = std::vector<int>(N, std::numeric_limits<int>::min());
      
      current_statement__ = 33;
      assign(y, nil_index_list(), context__.vals_i("y"),
        "assigning variable y");
      current_statement__ = 33;
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 33;
        current_statement__ = 33;
        check_greater_or_equal(function__, "y[sym1__]", y[(sym1__ - 1)], 0);}
      current_statement__ = 34;
      validate_non_negative_index("EloStart_raw", "n_rand", n_rand);
      current_statement__ = 35;
      validate_non_negative_index("EloStart_raw", "K", K);
      current_statement__ = 36;
      validate_non_negative_index("EloStart", "n_rand", n_rand);
      current_statement__ = 37;
      validate_non_negative_index("EloStart", "K", K);
      current_statement__ = 38;
      validate_non_negative_index("steepness", "n_rand", n_rand);
      current_statement__ = 39;
      validate_non_negative_index("cumwinprobs", "n_rand", n_rand);
      current_statement__ = 40;
      validate_non_negative_index("cumwinprobs", "K", K);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    num_params_r__ = 0U;
    
    try {
      num_params_r__ += n_rand * K;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI, stan::require_vector_like_t<VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    static const char* function__ = "model_multi_steep_fixed_sd_fixed_k_namespace::log_prob";
(void) function__;  // suppress unused var warning
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      Eigen::Matrix<local_scalar_t__, -1, -1> EloStart_raw;
      EloStart_raw = Eigen::Matrix<local_scalar_t__, -1, -1>(n_rand, K);
      stan::math::fill(EloStart_raw, DUMMY_VAR__);
      
      current_statement__ = 1;
      EloStart_raw = in__.matrix(n_rand, K);
      Eigen::Matrix<local_scalar_t__, -1, -1> EloStart;
      EloStart = Eigen::Matrix<local_scalar_t__, -1, -1>(n_rand, K);
      stan::math::fill(EloStart, DUMMY_VAR__);
      
      current_statement__ = 7;
      for (int r = 1; r <= n_rand; ++r) {
        current_statement__ = 5;
        for (int i = 1; i <= K; ++i) {
          current_statement__ = 3;
          assign(EloStart,
            cons_list(index_uni(r),
              cons_list(index_uni(i), nil_index_list())),
            (rvalue(EloStart_raw,
               cons_list(index_uni(r),
                 cons_list(index_uni(i), nil_index_list())), "EloStart_raw")
              -
              mean(
                rvalue(EloStart_raw,
                  cons_list(index_uni(r),
                    cons_list(index_omni(), nil_index_list())),
                  "EloStart_raw"))), "assigning variable EloStart");}}
      {
        current_statement__ = 17;
        for (int r = 1; r <= n_rand; ++r) {
          current_statement__ = 14;
          lp_accum__.add(
            normal_lpdf<propto__>(
              rvalue(EloStart_raw,
                cons_list(index_uni(r),
                  cons_list(index_omni(), nil_index_list())), "EloStart_raw"),
              0, 1));
          current_statement__ = 15;
          lp_accum__.add(
            bernoulli_lpmf<propto__>(y,
              ProbFunction(
                to_vector(
                  rvalue(EloStart,
                    cons_list(index_uni(r),
                      cons_list(index_omni(), nil_index_list())), "EloStart")),
                k[(r - 1)], presence, N, K,
                rvalue(winner,
                  cons_list(index_omni(),
                    cons_list(index_uni(r), nil_index_list())), "winner"),
                rvalue(loser,
                  cons_list(index_omni(),
                    cons_list(index_uni(r), nil_index_list())), "loser"), pstream__)));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr>
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.resize(0);
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    static const char* function__ = "model_multi_steep_fixed_sd_fixed_k_namespace::write_array";
(void) function__;  // suppress unused var warning
    (void) function__;  // suppress unused var warning
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      Eigen::Matrix<double, -1, -1> EloStart_raw;
      EloStart_raw = Eigen::Matrix<double, -1, -1>(n_rand, K);
      stan::math::fill(EloStart_raw, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 1;
      EloStart_raw = in__.matrix(n_rand, K);
      Eigen::Matrix<double, -1, -1> EloStart;
      EloStart = Eigen::Matrix<double, -1, -1>(n_rand, K);
      stan::math::fill(EloStart, std::numeric_limits<double>::quiet_NaN());
      
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= n_rand; ++sym2__) {
          vars__.emplace_back(
            rvalue(EloStart_raw,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              "EloStart_raw"));}}
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      current_statement__ = 7;
      for (int r = 1; r <= n_rand; ++r) {
        current_statement__ = 5;
        for (int i = 1; i <= K; ++i) {
          current_statement__ = 3;
          assign(EloStart,
            cons_list(index_uni(r),
              cons_list(index_uni(i), nil_index_list())),
            (rvalue(EloStart_raw,
               cons_list(index_uni(r),
                 cons_list(index_uni(i), nil_index_list())), "EloStart_raw")
              -
              mean(
                rvalue(EloStart_raw,
                  cons_list(index_uni(r),
                    cons_list(index_omni(), nil_index_list())),
                  "EloStart_raw"))), "assigning variable EloStart");}}
      if (emit_transformed_parameters__) {
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= n_rand; ++sym2__) {
            vars__.emplace_back(
              rvalue(EloStart,
                cons_list(index_uni(sym2__),
                  cons_list(index_uni(sym1__), nil_index_list())),
                "EloStart"));}}
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
      Eigen::Matrix<double, -1, 1> steepness;
      steepness = Eigen::Matrix<double, -1, 1>(n_rand);
      stan::math::fill(steepness, std::numeric_limits<double>::quiet_NaN());
      
      Eigen::Matrix<double, -1, -1> cumwinprobs;
      cumwinprobs = Eigen::Matrix<double, -1, -1>(n_rand, K);
      stan::math::fill(cumwinprobs, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 13;
      for (int r = 1; r <= n_rand; ++r) {
        current_statement__ = 10;
        assign(cumwinprobs,
          cons_list(index_uni(r), cons_list(index_omni(), nil_index_list())),
          to_row_vector(
            cum_winprob(
              to_vector(
                rvalue(EloStart,
                  cons_list(index_uni(r),
                    cons_list(index_omni(), nil_index_list())), "EloStart")),
              k[(r - 1)], N, K,
              rvalue(winner,
                cons_list(index_omni(),
                  cons_list(index_uni(r), nil_index_list())), "winner"),
              rvalue(loser,
                cons_list(index_omni(),
                  cons_list(index_uni(r), nil_index_list())), "loser"), pstream__)),
          "assigning variable cumwinprobs");
        current_statement__ = 11;
        assign(steepness, cons_list(index_uni(r), nil_index_list()),
          cumwinprob2steep(
  to_vector(
    rvalue(cumwinprobs,
      cons_list(index_uni(r), cons_list(index_omni(), nil_index_list())),
      "cumwinprobs")), K, pstream__)[
          (2 - 1)], "assigning variable steepness");}
      for (int sym1__ = 1; sym1__ <= n_rand; ++sym1__) {
        vars__.emplace_back(steepness[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= n_rand; ++sym2__) {
          vars__.emplace_back(
            rvalue(cumwinprobs,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              "cumwinprobs"));}}
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, stan::require_std_vector_t<VecVar>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void transform_inits_impl(const stan::io::var_context& context__,
                                   VecI& params_i__, VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.clear();
    vars__.reserve(num_params_r__);
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      Eigen::Matrix<double, -1, -1> EloStart_raw;
      EloStart_raw = Eigen::Matrix<double, -1, -1>(n_rand, K);
      stan::math::fill(EloStart_raw, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> EloStart_raw_flat__;
        current_statement__ = 1;
        assign(EloStart_raw_flat__, nil_index_list(),
          context__.vals_r("EloStart_raw"),
          "assigning variable EloStart_raw_flat__");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 1;
          for (int sym2__ = 1; sym2__ <= n_rand; ++sym2__) {
            current_statement__ = 1;
            assign(EloStart_raw,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              EloStart_raw_flat__[(pos__ - 1)],
              "assigning variable EloStart_raw");
            current_statement__ = 1;
            pos__ = (pos__ + 1);}}
      }
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= n_rand; ++sym2__) {
          vars__.emplace_back(
            rvalue(EloStart_raw,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              "EloStart_raw"));}}
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__.clear();
    names__.emplace_back("EloStart_raw");
    names__.emplace_back("EloStart");
    names__.emplace_back("steepness");
    names__.emplace_back("cumwinprobs");
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    dimss__.clear();
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(n_rand),
                                             static_cast<size_t>(K)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(n_rand),
                                             static_cast<size_t>(K)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(n_rand)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(n_rand),
                                             static_cast<size_t>(K)});
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      {
        for (int sym2__ = 1; sym2__ <= n_rand; ++sym2__) {
          {
            param_names__.emplace_back(std::string() + "EloStart_raw" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
          }}
      }}
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= n_rand; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "EloStart" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= n_rand; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "steepness" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= n_rand; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "cumwinprobs" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      {
        for (int sym2__ = 1; sym2__ <= n_rand; ++sym2__) {
          {
            param_names__.emplace_back(std::string() + "EloStart_raw" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
          }}
      }}
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= n_rand; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "EloStart" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= n_rand; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "steepness" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= n_rand; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "cumwinprobs" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"EloStart_raw\",\"type\":{\"name\":\"matrix\",\"rows\":" << n_rand << ",\"cols\":" << K << "},\"block\":\"parameters\"},{\"name\":\"EloStart\",\"type\":{\"name\":\"matrix\",\"rows\":" << n_rand << ",\"cols\":" << K << "},\"block\":\"transformed_parameters\"},{\"name\":\"steepness\",\"type\":{\"name\":\"vector\",\"length\":" << n_rand << "},\"block\":\"generated_quantities\"},{\"name\":\"cumwinprobs\",\"type\":{\"name\":\"matrix\",\"rows\":" << n_rand << ",\"cols\":" << K << "},\"block\":\"generated_quantities\"}]";
    return s__.str();
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"EloStart_raw\",\"type\":{\"name\":\"matrix\",\"rows\":" << n_rand << ",\"cols\":" << K << "},\"block\":\"parameters\"},{\"name\":\"EloStart\",\"type\":{\"name\":\"matrix\",\"rows\":" << n_rand << ",\"cols\":" << K << "},\"block\":\"transformed_parameters\"},{\"name\":\"steepness\",\"type\":{\"name\":\"vector\",\"length\":" << n_rand << "},\"block\":\"generated_quantities\"},{\"name\":\"cumwinprobs\",\"type\":{\"name\":\"matrix\",\"rows\":" << n_rand << ",\"cols\":" << K << "},\"block\":\"generated_quantities\"}]";
    return s__.str();
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      std::vector<double> vars_vec(vars.size());
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i) {
        vars.coeffRef(i) = vars_vec[i];
      }
    }
    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }
    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
  
    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits_impl(context, params_i, params_r_vec, pstream);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i) {
        params_r.coeffRef(i) = params_r_vec[i];
      }
    }
    inline void transform_inits(const stan::io::var_context& context,
                                std::vector<int>& params_i,
                                std::vector<double>& vars,
                                std::ostream* pstream = nullptr) const final {
      transform_inits_impl(context, params_i, vars, pstream);
    }        
};
}
using stan_model = model_multi_steep_fixed_sd_fixed_k_namespace::model_multi_steep_fixed_sd_fixed_k;
#ifndef USING_R
// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_multi_steep_fixed_sd_fixed_k_namespace::profiles__;
}
#endif
#endif
